name: ColoredPlayerNames
version: 0.5
description: A very simple plugin that colors players' names randomly on join
author: fvoichick
website: http://dev.bukkit.org/bukkit-plugins/coloredplayernames/
main: com.finnv3.coloredplayernames.ColoredPlayerNames
permissions:
  coloredplayernames.black:
    description: Sets a player's name to permanently be colored black
  coloredplayernames.dark_blue:
    description: Sets a player's name to permanently be colored dark blue
  coloredplayernames.dark_green:
    description: Sets a player's name to permanently be colored dark green
  coloredplayernames.dark_aqua:
    description: Sets a player's name to permanently be colored dark aqua
  coloredplayernames.dark_red:
    description: Sets a player's name to permanently be colored dark red
  coloredplayernames.dark_purple:
    description: Sets a player's name to permanently be colored dark purple
  coloredplayernames.gold:
    description: Sets a player's name to permanently be colored gold
  coloredplayernames.gray:
    description: Sets a player's name to permanently be colored gray
  coloredplayernames.dark_gray:
    description: Sets a player's name to permanently be colored dark gray
  coloredplayernames.blue:
    description: Sets a player's name to permanently be colored blue
  coloredplayernames.green:
    description: Sets a player's name to permanently be colored green
  coloredplayernames.aqua:
    description: Sets a player's name to permanently be colored aqua
  coloredplayernames.red:
    description: Sets a player's name to permanently be colored red
  coloredplayernames.light_purple:
    description: Sets a player's name to permanently be colored light purple
  coloredplayernames.yellow:
    description: Sets a player's name to permanently be colored yellow
  coloredplayernames.white:
    description: Sets a player's name to permanently be colored white
  coloredplayernames.obfuscated:
    description: Sets a player's name to permanently be obfuscated
  coloredplayernames.bold:
    description: Sets a player's name to permanently be bold
  coloredplayernames.strikethrough:
    description: Sets a player's name to permanently be crossed out
  coloredplayernames.underline:
    description: Sets a player's name to permanently be underlined
  coloredplayernames.italic:
    description: Sets a player's name to permanently be italicized
    